--========================================================================================================================
--========================================================================================================================
		INSERT OR REPLACE INTO LocalizedText
			(Tag,	Language,	Text)
		VALUES
			('LOC_SUK_SUA_YOUR_UNIT',		'en_US',	"Yours"),
			('LOC_SUK_SUA_DISTRICT',		'en_US',	"{1_Type} District"),
			('LOC_SUK_SUA_QUARTER',			'en_US',	"{1_Type} Quarter"),
			('LOC_SUK_SUA_PLOT_OWNERSHIP',	'en_US',	"{1} {LOC_PLOT_DIVIDER_DOT} {2} ({3})"),
			('LOC_SUK_SUA_IMPROVED_BY',		'en_US',	"Improve with: {1}"),
			('LOC_SUK_SUA_OBSOLETE',		'en_US',	"Obsolete"),
			('LOC_SUK_SUA_UNIMPROVED',		'en_US',	"Unimproved"),
			('LOC_SUK_SUA_GROWTH_TT',		'en_US',	"{1}/{2}[icon:YIELD_Food] ({3}[icon:YIELD_Food])"),
			('LOC_SUK_SUA_ADJ_QUARTER',		'en_US',	"Quarter"),

			('LOC_SUK_SUA_PLACE_BLD_KEY',			'en_US',	"Key"),
			('LOC_SUK_SUA_PLACE_BLD_ADJACENCIES',	'en_US',	"This Building’s adjacency bonuses."),
			('LOC_SUK_SUA_PLACE_BLD_WORKERS',		'en_US',	"Specialists multiplying this building’s adjacency bonuses."),
			('LOC_SUK_SUA_PLACE_BLD_TO_OTHERS',		'en_US',	"Adjacency bonuses to other Tiles."),
			('LOC_SUK_SUA_PLACE_BLD_BASE_YIELD',	'en_US',	"This Building’s Base Yield."),
			('LOC_SUK_SUA_PLACE_BLD_WAREHOUSE',		'en_US',	"Warehouse bonuses to other Tiles."),
			('LOC_SUK_SUA_PLACE_BLD_OVERBUILD',		'en_US',	"Yield losses from Overbuilding/developing a Rural Tile."),
			('LOC_SUK_SUA_PLACE_BLD_UNWORKED',		'en_US',	"Opportunity cost from developing an unworked tile."),
			-- Spanish --
			('LOC_SUK_SUA_YOUR_UNIT',		'es_ES',	"Tuyo"),
			('LOC_SUK_SUA_DISTRICT',		'es_ES',	"Distrito {1_Type}"),
			('LOC_SUK_SUA_QUARTER',			'es_ES',	"Barrio {1_Type}"),
			('LOC_SUK_SUA_PLOT_OWNERSHIP',	'es_ES',	"{1} {LOC_PLOT_DIVIDER_DOT} {2} ({3})"),
			('LOC_SUK_SUA_IMPROVED_BY',		'es_ES',	"Mejorado con: {1}"),
			('LOC_SUK_SUA_OBSOLETE',		'es_ES',	"Obsoleto"),
			('LOC_SUK_SUA_UNIMPROVED',		'es_ES',	"Sin mejoras"),
			('LOC_SUK_SUA_GROWTH_TT',		'es_ES',	"{1}/{2}[icon:YIELD_Food] ({3}[icon:YIELD_Food])"),
			('LOC_SUK_SUA_ADJ_QUARTER',		'es_ES',	"Barrio"),
			-- Chinese (Simplified) --
			('LOC_SUK_SUA_YOUR_UNIT',		'zh_Hans_CN',	"你的"),
			('LOC_SUK_SUA_DISTRICT',		'zh_Hans_CN',	"{1_Type}区块"),
			('LOC_SUK_SUA_QUARTER',			'zh_Hans_CN',	"{1_Type}城区"),
			('LOC_SUK_SUA_PLOT_OWNERSHIP',	'zh_Hans_CN',	"{1} {LOC_PLOT_DIVIDER_DOT} {2} ({3})"),
			('LOC_SUK_SUA_IMPROVED_BY',		'zh_Hans_CN',	"预期的改良设施: {1}"),
			('LOC_SUK_SUA_OBSOLETE',		'zh_Hans_CN',	"过时"),
			('LOC_SUK_SUA_UNIMPROVED',		'zh_Hans_CN',	"无改良设施"),
			('LOC_SUK_SUA_GROWTH_TT',		'zh_Hans_CN',	"{1}/{2}[icon:YIELD_Food] ({3}[icon:YIELD_Food])"),
			('LOC_SUK_SUA_ADJ_QUARTER',		'zh_Hans_CN',	"城区"),
			-- Japanese --
			('LOC_SUK_SUA_YOUR_UNIT',		'ja_JP',	"あなた"),
			('LOC_SUK_SUA_DISTRICT',		'ja_JP',	"{1_Type} 区域"),
			('LOC_SUK_SUA_QUARTER',			'ja_JP',	"{1_Type} 街区"),
			('LOC_SUK_SUA_PLOT_OWNERSHIP',	'ja_JP',	"{1} {LOC_PLOT_DIVIDER_DOT} {2} ({3})"),
			('LOC_SUK_SUA_IMPROVED_BY',		'ja_JP',	"{1} により改善"),
			('LOC_SUK_SUA_OBSOLETE',		'ja_JP',	"時代遅れ"),
			('LOC_SUK_SUA_UNIMPROVED',		'ja_JP',	"未改善"),
			('LOC_SUK_SUA_GROWTH_TT',		'ja_JP',	"{1}/{2}[icon:YIELD_Food] ({3}[icon:YIELD_Food])"),
			('LOC_SUK_SUA_ADJ_QUARTER',		'ja_JP',	"街区"),
			-- Italian --
			('LOC_SUK_SUA_YOUR_UNIT',		'it_IT',	"Tuoi"),
			('LOC_SUK_SUA_DISTRICT',		'it_IT',	"Distretto {1_Type}"),
			('LOC_SUK_SUA_QUARTER',			'it_IT',	"Quartiere {1_Type}"),
			('LOC_SUK_SUA_PLOT_OWNERSHIP',	'it_IT',	"{1} {LOC_PLOT_DIVIDER_DOT} {2} ({3})"),
			('LOC_SUK_SUA_IMPROVED_BY',		'it_IT',	"Migliorato con: {1}"),
			('LOC_SUK_SUA_OBSOLETE',		'it_IT',	"Obsoleto"),
			('LOC_SUK_SUA_UNIMPROVED',		'it_IT',	"Non migliorato"),
			('LOC_SUK_SUA_GROWTH_TT',		'it_IT',	"{1}/{2}[icon:YIELD_Food] ({3}[icon:YIELD_Food])"),
			('LOC_SUK_SUA_ADJ_QUARTER',		'it_IT',	"Quartiere"),
			-- Polish --
			('LOC_SUK_SUA_YOUR_UNIT',		'pl_PL',	"Twoja"),
			('LOC_SUK_SUA_DISTRICT',		'pl_PL',	"{1_Type} Dystrykt"),
			('LOC_SUK_SUA_QUARTER',			'pl_PL',	"{1_Type} Dzielnica"),
			('LOC_SUK_SUA_PLOT_OWNERSHIP',	'pl_PL',	"{1} {LOC_PLOT_DIVIDER_DOT} {2} ({3})"),
			('LOC_SUK_SUA_IMPROVED_BY',		'pl_PL',	"Dostępne ulepszenie: {1}"),
			('LOC_SUK_SUA_OBSOLETE',		'pl_PL',	"Przestarzałe"),
			('LOC_SUK_SUA_UNIMPROVED',		'pl_PL',	"Puste pole"),
			('LOC_SUK_SUA_GROWTH_TT',		'pl_PL',	"{1}/{2}[icon:YIELD_Food] ({3}[icon:YIELD_Food])"),
			('LOC_SUK_SUA_ADJ_QUARTER',		'pl_PL',	"Dzielnica"),
			-- Russian --
			('LOC_SUK_SUA_YOUR_UNIT',		'ru_RU',	"ваш"),
			('LOC_SUK_SUA_DISTRICT',		'ru_RU',	"{1_Type} Район"),
			('LOC_SUK_SUA_QUARTER',			'ru_RU',	"{1_Type} Квартал"),
			('LOC_SUK_SUA_PLOT_OWNERSHIP',	'ru_RU',	"{1} {LOC_PLOT_DIVIDER_DOT} {2} ({3})"),
			('LOC_SUK_SUA_IMPROVED_BY',		'ru_RU',	"Улучшает: {1}"),
			('LOC_SUK_SUA_OBSOLETE',		'ru_RU',	"Устарело"),
			('LOC_SUK_SUA_UNIMPROVED',		'ru_RU',	"Не улучшено"),
			('LOC_SUK_SUA_GROWTH_TT',		'ru_RU',	"{1}/{2}[icon:YIELD_Food] ({3}[icon:YIELD_Food])"),
			('LOC_SUK_SUA_ADJ_QUARTER',		'ru_RU',	"Квартал");
--========================================================================================================================
--========================================================================================================================