INSERT OR REPLACE INTO LocalizedText
	(Tag,	Language,	Text)
VALUES
	('LOC_SEN_UI_UNIT_MAN_VIEW_UNITS',		'en_US',	"View Units"),	
	('LOC_SEN_UI_UNIT_MANAGEMENT_HEADER',	'en_US',	"Unit Management"),	
	('LOC_SEN_UI_UNIT_MAN_LANDUNITS',		'en_US',	"Land Units"),	
	('LOC_SEN_UI_UNIT_MAN_AIRUNITS',		'en_US',	"Air Units"),	
	('LOC_SEN_UI_UNIT_MAN_NAVALUNITS',		'en_US',	"Naval Units"),	
	('LOC_SEN_UI_UNIT_MAN_MILITARY_TAB',	'en_US',	"Military"),	
	('LOC_SEN_UI_UNIT_MAN_RELIGIOUS_TAB',	'en_US',	"Religious"),	
	('LOC_SEN_UI_UNIT_MAN_CIVILIAN_TAB',	'en_US',	"Civilian"),
	('LOC_SEN_UI_UNIT_MAN_GO_TO_UNIT',		'en_US',	"Go to unit"),
	('LOC_SEN_UI_UNIT_MAN_UNIT_NAME',		'en_US',	"Unit Name"),
	('LOC_SEN_UI_UNIT_MAN_HEALTH_HEADER',	'en_US',	"Health"),
	('LOC_SEN_UI_UNIT_MAN_CURRENT_COMMAND',	'en_US',	"Current Command"),
	('LOC_SEN_UI_UNIT_MAN_UPGRADE_PROMOTE',	'en_US',	"Upgrade or Promotion Available"),
	('LOC_SEN_UI_UNIT_MAN_EXP_TOOLTIP',		'en_US',	"Experience:"),
	('LOC_SEN_UI_UNIT_MAN_NOMILITARYUNITS',	'en_US',	"You currently have no military units"),
	('LOC_SEN_UI_UNIT_MAN_NORELIGIOUSUNITS','en_US',	"You currently have no religious units"),
	('LOC_SEN_UI_UNIT_MAN_NOCIVILIANUNITS',	'en_US',	"You currently have no civilian units"),
	('LOC_SEN_UI_UNIT_MAN_SPREADS_TOOLTIP',	'en_US',	"Spreads Remaining"),
	-- Spanish
	('LOC_SEN_UI_UNIT_MAN_VIEW_UNITS',		'es_ES',	"Ver unidades"),	
	('LOC_SEN_UI_UNIT_MANAGEMENT_HEADER',	'es_ES',	"Gestión de unidades"),	
	('LOC_SEN_UI_UNIT_MAN_LANDUNITS',		'es_ES',	"Unidades de Tierra"),	
	('LOC_SEN_UI_UNIT_MAN_AIRUNITS',		'es_ES',	"Unidades Aéreas"),	
	('LOC_SEN_UI_UNIT_MAN_NAVALUNITS',		'es_ES',	"Unidades Navales"),	
	('LOC_SEN_UI_UNIT_MAN_MILITARY_TAB',	'es_ES',	"Militar"),	
	('LOC_SEN_UI_UNIT_MAN_RELIGIOUS_TAB',	'es_ES',	"Religiosas"),	
	('LOC_SEN_UI_UNIT_MAN_CIVILIAN_TAB',	'es_ES',	"Civil"),
	('LOC_SEN_UI_UNIT_MAN_GO_TO_UNIT',		'es_ES',	"Ir a la unidad"),
	('LOC_SEN_UI_UNIT_MAN_UNIT_NAME',		'es_ES',	"Nombre de la unidad"),
	('LOC_SEN_UI_UNIT_MAN_HEALTH_HEADER',	'es_ES',	"Salud"),
	('LOC_SEN_UI_UNIT_MAN_CURRENT_COMMAND',	'es_ES',	"Comando actual"),
	('LOC_SEN_UI_UNIT_MAN_UPGRADE_PROMOTE',	'es_ES',	"Actualización o promoción disponible"),
	('LOC_SEN_UI_UNIT_MAN_EXP_TOOLTIP',		'es_ES',	"Experiencia:"),
	('LOC_SEN_UI_UNIT_MAN_NOMILITARYUNITS',	'es_ES',	"Actualmente no tienes unidades militares"),
	('LOC_SEN_UI_UNIT_MAN_NORELIGIOUSUNITS','es_ES',	"Actualmente no tienes unidades religiosas"),
	('LOC_SEN_UI_UNIT_MAN_NOCIVILIANUNITS',	'es_ES',	"Actualmente no tienes unidades civiles"),
	('LOC_SEN_UI_UNIT_MAN_SPREADS_TOOLTIP',	'es_ES',	"Spreads restantes"),
	-- Chinese Simplified
	('LOC_SEN_UI_UNIT_MAN_VIEW_UNITS',		'zh_Hans_CN',	"查看单位"),	
	('LOC_SEN_UI_UNIT_MANAGEMENT_HEADER',	'zh_Hans_CN',	"单位管理"),	
	('LOC_SEN_UI_UNIT_MAN_LANDUNITS',		'zh_Hans_CN',	"土地单位"),	
	('LOC_SEN_UI_UNIT_MAN_AIRUNITS',		'zh_Hans_CN',	"空气单位"),	
	('LOC_SEN_UI_UNIT_MAN_NAVALUNITS',		'zh_Hans_CN',	"海军单位"),	
	('LOC_SEN_UI_UNIT_MAN_MILITARY_TAB',	'zh_Hans_CN',	"军队"),	
	('LOC_SEN_UI_UNIT_MAN_RELIGIOUS_TAB',	'zh_Hans_CN',	"宗教"),	
	('LOC_SEN_UI_UNIT_MAN_CIVILIAN_TAB',	'zh_Hans_CN',	"平民"),
	('LOC_SEN_UI_UNIT_MAN_GO_TO_UNIT',		'zh_Hans_CN',	"去单位"),
	('LOC_SEN_UI_UNIT_MAN_UNIT_NAME',		'zh_Hans_CN',	"单位名称"),
	('LOC_SEN_UI_UNIT_MAN_HEALTH_HEADER',	'zh_Hans_CN',	"健康"),
	('LOC_SEN_UI_UNIT_MAN_CURRENT_COMMAND',	'zh_Hans_CN',	"当前命令"),
	('LOC_SEN_UI_UNIT_MAN_UPGRADE_PROMOTE',	'zh_Hans_CN',	"提供升级或促销"),
	('LOC_SEN_UI_UNIT_MAN_EXP_TOOLTIP',		'zh_Hans_CN',	"经验："),
	('LOC_SEN_UI_UNIT_MAN_NOMILITARYUNITS',	'zh_Hans_CN',	"您目前没有军事单位"),
	('LOC_SEN_UI_UNIT_MAN_NORELIGIOUSUNITS','zh_Hans_CN',	"您目前没有宗教单位"),
	('LOC_SEN_UI_UNIT_MAN_NOCIVILIANUNITS',	'zh_Hans_CN',	"您目前没有平民单位"),
	('LOC_SEN_UI_UNIT_MAN_SPREADS_TOOLTIP',	'zh_Hans_CN',	"剩余利差"),
	-- Chinese Traditional
	('LOC_SEN_UI_UNIT_MAN_VIEW_UNITS',		'zh_Hant_HK',	"查看單位"),	
	('LOC_SEN_UI_UNIT_MANAGEMENT_HEADER',	'zh_Hant_HK',	"單位管理"),	
	('LOC_SEN_UI_UNIT_MAN_LANDUNITS',		'zh_Hant_HK',	"土地單位"),	
	('LOC_SEN_UI_UNIT_MAN_AIRUNITS',		'zh_Hant_HK',	"空氣單位"),	
	('LOC_SEN_UI_UNIT_MAN_NAVALUNITS',		'zh_Hant_HK',	"海軍單位"),	
	('LOC_SEN_UI_UNIT_MAN_MILITARY_TAB',	'zh_Hant_HK',	"軍隊"),	
	('LOC_SEN_UI_UNIT_MAN_RELIGIOUS_TAB',	'zh_Hant_HK',	"宗教"),	
	('LOC_SEN_UI_UNIT_MAN_CIVILIAN_TAB',	'zh_Hant_HK',	"平民"),
	('LOC_SEN_UI_UNIT_MAN_GO_TO_UNIT',		'zh_Hant_HK',	"去單位"),
	('LOC_SEN_UI_UNIT_MAN_UNIT_NAME',		'zh_Hant_HK',	"單位名稱"),
	('LOC_SEN_UI_UNIT_MAN_HEALTH_HEADER',	'zh_Hant_HK',	"健康"),
	('LOC_SEN_UI_UNIT_MAN_CURRENT_COMMAND',	'zh_Hant_HK',	"目前命令"),
	('LOC_SEN_UI_UNIT_MAN_UPGRADE_PROMOTE',	'zh_Hant_HK',	"提供升級或促銷"),
	('LOC_SEN_UI_UNIT_MAN_EXP_TOOLTIP',		'zh_Hant_HK',	"經驗："),
	('LOC_SEN_UI_UNIT_MAN_NOMILITARYUNITS',	'zh_Hant_HK',	"您目前沒有軍事單位"),
	('LOC_SEN_UI_UNIT_MAN_NORELIGIOUSUNITS','zh_Hant_HK',	"您目前沒有宗教單位"),
	('LOC_SEN_UI_UNIT_MAN_NOCIVILIANUNITS',	'zh_Hant_HK',	"您目前沒有平民單位"),
	('LOC_SEN_UI_UNIT_MAN_SPREADS_TOOLTIP',	'zh_Hant_HK',	"剩餘利差"),
	-- Japanese
	('LOC_SEN_UI_UNIT_MAN_VIEW_UNITS',		'ja_JP',	"ユニットの表示"),	
	('LOC_SEN_UI_UNIT_MANAGEMENT_HEADER',	'ja_JP',	"ユニット管理"),	
	('LOC_SEN_UI_UNIT_MAN_LANDUNITS',		'ja_JP',	"陸上ユニット"),	
	('LOC_SEN_UI_UNIT_MAN_AIRUNITS',		'ja_JP',	"航空ユニット"),	
	('LOC_SEN_UI_UNIT_MAN_NAVALUNITS',		'ja_JP',	"海軍部隊"),	
	('LOC_SEN_UI_UNIT_MAN_MILITARY_TAB',	'ja_JP',	"軍隊"),	
	('LOC_SEN_UI_UNIT_MAN_RELIGIOUS_TAB',	'ja_JP',	"宗教的"),	
	('LOC_SEN_UI_UNIT_MAN_CIVILIAN_TAB',	'ja_JP',	"民間人"),
	('LOC_SEN_UI_UNIT_MAN_GO_TO_UNIT',		'ja_JP',	"ユニットに移動"),
	('LOC_SEN_UI_UNIT_MAN_UNIT_NAME',		'ja_JP',	"ユニット名"),
	('LOC_SEN_UI_UNIT_MAN_HEALTH_HEADER',	'ja_JP',	"健康"),
	('LOC_SEN_UI_UNIT_MAN_CURRENT_COMMAND',	'ja_JP',	"現在のコマンド"),
	('LOC_SEN_UI_UNIT_MAN_UPGRADE_PROMOTE',	'ja_JP',	"アップグレードまたはプロモーションが利用可能"),
	('LOC_SEN_UI_UNIT_MAN_EXP_TOOLTIP',		'ja_JP',	"経験："),
	('LOC_SEN_UI_UNIT_MAN_NOMILITARYUNITS',	'ja_JP',	"現在、軍事ユニットはありません"),
	('LOC_SEN_UI_UNIT_MAN_NORELIGIOUSUNITS','ja_JP',	"現在、宗教ユニットはありません"),
	('LOC_SEN_UI_UNIT_MAN_NOCIVILIANUNITS',	'ja_JP',	"現在、民間ユニットはありません"),
	('LOC_SEN_UI_UNIT_MAN_SPREADS_TOOLTIP',	'ja_JP',	"残りのスプレッド"),
	-- Korean
	('LOC_SEN_UI_UNIT_MAN_VIEW_UNITS',		'ko_KR',	"단위 보기"),	
	('LOC_SEN_UI_UNIT_MANAGEMENT_HEADER',	'ko_KR',	"단위 관리"),	
	('LOC_SEN_UI_UNIT_MAN_LANDUNITS',		'ko_KR',	"토지 유닛"),	
	('LOC_SEN_UI_UNIT_MAN_AIRUNITS',		'ko_KR',	"공중 유닛"),	
	('LOC_SEN_UI_UNIT_MAN_NAVALUNITS',		'ko_KR',	"해군 부대"),	
	('LOC_SEN_UI_UNIT_MAN_MILITARY_TAB',	'ko_KR',	"군대"),	
	('LOC_SEN_UI_UNIT_MAN_RELIGIOUS_TAB',	'ko_KR',	"종교의"),	
	('LOC_SEN_UI_UNIT_MAN_CIVILIAN_TAB',	'ko_KR',	"일반 민간인"),
	('LOC_SEN_UI_UNIT_MAN_GO_TO_UNIT',		'ko_KR',	"유닛으로 이동"),
	('LOC_SEN_UI_UNIT_MAN_UNIT_NAME',		'ko_KR',	"단위 이름"),
	('LOC_SEN_UI_UNIT_MAN_HEALTH_HEADER',	'ko_KR',	"건강"),
	('LOC_SEN_UI_UNIT_MAN_CURRENT_COMMAND',	'ko_KR',	"현재 명령"),
	('LOC_SEN_UI_UNIT_MAN_UPGRADE_PROMOTE',	'ko_KR',	"업그레이드 또는 프로모션 가능"),
	('LOC_SEN_UI_UNIT_MAN_EXP_TOOLTIP',		'ko_KR',	"경험:"),
	('LOC_SEN_UI_UNIT_MAN_NOMILITARYUNITS',	'ko_KR',	"현재 군사 유닛이 없습니다"),
	('LOC_SEN_UI_UNIT_MAN_NORELIGIOUSUNITS','ko_KR',	"현재 종교 단위가 없습니다."),
	('LOC_SEN_UI_UNIT_MAN_NOCIVILIANUNITS',	'ko_KR',	"현재 민간인 유닛이 없습니다."),
	('LOC_SEN_UI_UNIT_MAN_SPREADS_TOOLTIP',	'ko_KR',	"남은 스프레드"),
	-- French
	('LOC_SEN_UI_UNIT_MAN_VIEW_UNITS',		'fr_FR',	"Afficher les unités"),	
	('LOC_SEN_UI_UNIT_MANAGEMENT_HEADER',	'fr_FR',	"Gestion de l'unité"),	
	('LOC_SEN_UI_UNIT_MAN_LANDUNITS',		'fr_FR',	"Unités terrestres"),	
	('LOC_SEN_UI_UNIT_MAN_AIRUNITS',		'fr_FR',	"Unités aériennes"),	
	('LOC_SEN_UI_UNIT_MAN_NAVALUNITS',		'fr_FR',	"Unités navales"),	
	('LOC_SEN_UI_UNIT_MAN_MILITARY_TAB',	'fr_FR',	"Militaire"),	
	('LOC_SEN_UI_UNIT_MAN_RELIGIOUS_TAB',	'fr_FR',	"Religieuse"),	
	('LOC_SEN_UI_UNIT_MAN_CIVILIAN_TAB',	'fr_FR',	"Civile"),
	('LOC_SEN_UI_UNIT_MAN_GO_TO_UNIT',		'fr_FR',	"Aller à l'unité"),
	('LOC_SEN_UI_UNIT_MAN_UNIT_NAME',		'fr_FR',	"Nom de l'unité"),
	('LOC_SEN_UI_UNIT_MAN_HEALTH_HEADER',	'fr_FR',	"Santé"),
	('LOC_SEN_UI_UNIT_MAN_CURRENT_COMMAND',	'fr_FR',	"Commande actuelle"),
	('LOC_SEN_UI_UNIT_MAN_UPGRADE_PROMOTE',	'fr_FR',	"Mise à niveau ou promotion disponible"),
	('LOC_SEN_UI_UNIT_MAN_EXP_TOOLTIP',		'fr_FR',	"Expérience:"),
	('LOC_SEN_UI_UNIT_MAN_NOMILITARYUNITS',	'fr_FR',	"Vous n'avez actuellement aucune unité militaire"),
	('LOC_SEN_UI_UNIT_MAN_NORELIGIOUSUNITS','fr_FR',	"Vous n'avez actuellement aucune unité religieuse"),
	('LOC_SEN_UI_UNIT_MAN_NOCIVILIANUNITS',	'fr_FR',	"Vous n'avez actuellement aucune unité civile"),
	('LOC_SEN_UI_UNIT_MAN_SPREADS_TOOLTIP',	'fr_FR',	"Spreads restants"),
	-- Italian
	('LOC_SEN_UI_UNIT_MAN_VIEW_UNITS',		'it_IT',	"Visualizza unità"),	
	('LOC_SEN_UI_UNIT_MANAGEMENT_HEADER',	'it_IT',	"Gestione dell'unità"),	
	('LOC_SEN_UI_UNIT_MAN_LANDUNITS',		'it_IT',	"Unità terrestri"),	
	('LOC_SEN_UI_UNIT_MAN_AIRUNITS',		'it_IT',	"Unità aeree"),	
	('LOC_SEN_UI_UNIT_MAN_NAVALUNITS',		'it_IT',	"Unità navali"),	
	('LOC_SEN_UI_UNIT_MAN_MILITARY_TAB',	'it_IT',	"Militare"),	
	('LOC_SEN_UI_UNIT_MAN_RELIGIOUS_TAB',	'it_IT',	"Religiosa"),	
	('LOC_SEN_UI_UNIT_MAN_CIVILIAN_TAB',	'it_IT',	"Civile"),
	('LOC_SEN_UI_UNIT_MAN_GO_TO_UNIT',		'it_IT',	"Vai all'unità"),
	('LOC_SEN_UI_UNIT_MAN_UNIT_NAME',		'it_IT',	"Nome dell'unità"),
	('LOC_SEN_UI_UNIT_MAN_HEALTH_HEADER',	'it_IT',	"Salute"),
	('LOC_SEN_UI_UNIT_MAN_CURRENT_COMMAND',	'it_IT',	"Comando attuale"),
	('LOC_SEN_UI_UNIT_MAN_UPGRADE_PROMOTE',	'it_IT',	"Aggiornamento o promozione disponibile"),
	('LOC_SEN_UI_UNIT_MAN_EXP_TOOLTIP',		'it_IT',	"Esperienza:"),
	('LOC_SEN_UI_UNIT_MAN_NOMILITARYUNITS',	'it_IT',	"Al momento non hai unità militari"),
	('LOC_SEN_UI_UNIT_MAN_NORELIGIOUSUNITS','it_IT',	"Al momento non hai unità religiose"),
	('LOC_SEN_UI_UNIT_MAN_NOCIVILIANUNITS',	'it_IT',	"Al momento non hai unità civili"),
	('LOC_SEN_UI_UNIT_MAN_SPREADS_TOOLTIP',	'it_IT',	"Spread rimanenti"),
	-- Polish
	('LOC_SEN_UI_UNIT_MAN_VIEW_UNITS',		'pl_PL',	"Zobacz jednostki"),	
	('LOC_SEN_UI_UNIT_MANAGEMENT_HEADER',	'pl_PL',	"Zarządzanie Jednostką"),	
	('LOC_SEN_UI_UNIT_MAN_LANDUNITS',		'pl_PL',	"Jednostki Lądowe"),	
	('LOC_SEN_UI_UNIT_MAN_AIRUNITS',		'pl_PL',	"Jednostki Powietrzne"),	
	('LOC_SEN_UI_UNIT_MAN_NAVALUNITS',		'pl_PL',	"Jednostki Morskie"),	
	('LOC_SEN_UI_UNIT_MAN_MILITARY_TAB',	'pl_PL',	"Wojskowy"),	
	('LOC_SEN_UI_UNIT_MAN_RELIGIOUS_TAB',	'pl_PL',	"Religijny"),	
	('LOC_SEN_UI_UNIT_MAN_CIVILIAN_TAB',	'pl_PL',	"Cywil"),
	('LOC_SEN_UI_UNIT_MAN_GO_TO_UNIT',		'pl_PL',	"Idź do jednostki"),
	('LOC_SEN_UI_UNIT_MAN_UNIT_NAME',		'pl_PL',	"Nazwa jednostki"),
	('LOC_SEN_UI_UNIT_MAN_HEALTH_HEADER',	'pl_PL',	"Zdrowie"),
	('LOC_SEN_UI_UNIT_MAN_CURRENT_COMMAND',	'pl_PL',	"Aktualne polecenie"),
	('LOC_SEN_UI_UNIT_MAN_UPGRADE_PROMOTE',	'pl_PL',	"Dostępna aktualizacja lub promocja"),
	('LOC_SEN_UI_UNIT_MAN_EXP_TOOLTIP',		'pl_PL',	"Doświadczenie:"),
	('LOC_SEN_UI_UNIT_MAN_NOMILITARYUNITS',	'pl_PL',	"Obecnie nie posiadasz żadnych jednostek wojskowych"),
	('LOC_SEN_UI_UNIT_MAN_NORELIGIOUSUNITS','pl_PL',	"Obecnie nie masz żadnych jednostek religijnych"),
	('LOC_SEN_UI_UNIT_MAN_NOCIVILIANUNITS',	'pl_PL',	"Obecnie nie posiadasz żadnych jednostek cywilnych"),
	('LOC_SEN_UI_UNIT_MAN_SPREADS_TOOLTIP',	'pl_PL',	"Pozostałe spready"),
	-- Russian
	('LOC_SEN_UI_UNIT_MAN_VIEW_UNITS',		'ru_RU',	"Просмотр единиц"),	
	('LOC_SEN_UI_UNIT_MANAGEMENT_HEADER',	'ru_RU',	"Управление подразделением"),	
	('LOC_SEN_UI_UNIT_MAN_LANDUNITS',		'ru_RU',	"Сухопутные единицы"),	
	('LOC_SEN_UI_UNIT_MAN_AIRUNITS',		'ru_RU',	"Воздушные подразделения"),	
	('LOC_SEN_UI_UNIT_MAN_NAVALUNITS',		'ru_RU',	"Военно-морские подразделения"),	
	('LOC_SEN_UI_UNIT_MAN_MILITARY_TAB',	'ru_RU',	"Военный"),	
	('LOC_SEN_UI_UNIT_MAN_RELIGIOUS_TAB',	'ru_RU',	"Религиозный"),	
	('LOC_SEN_UI_UNIT_MAN_CIVILIAN_TAB',	'ru_RU',	"Гражданский"),
	('LOC_SEN_UI_UNIT_MAN_GO_TO_UNIT',		'ru_RU',	"Перейти в подразделение"),
	('LOC_SEN_UI_UNIT_MAN_UNIT_NAME',		'ru_RU',	"Название устройства"),
	('LOC_SEN_UI_UNIT_MAN_HEALTH_HEADER',	'ru_RU',	"Здоровье"),
	('LOC_SEN_UI_UNIT_MAN_CURRENT_COMMAND',	'ru_RU',	"Текущая команда"),
	('LOC_SEN_UI_UNIT_MAN_UPGRADE_PROMOTE',	'ru_RU',	"Доступно обновление или повышение"),
	('LOC_SEN_UI_UNIT_MAN_EXP_TOOLTIP',		'ru_RU',	"Опыт:"),
	('LOC_SEN_UI_UNIT_MAN_NOMILITARYUNITS',	'ru_RU',	"В настоящее время у вас нет воинских частей"),
	('LOC_SEN_UI_UNIT_MAN_NORELIGIOUSUNITS','ru_RU',	"В настоящее время у вас нет религиозных подразделений"),
	('LOC_SEN_UI_UNIT_MAN_NOCIVILIANUNITS',	'ru_RU',	"В настоящее время у вас нет гражданских подразделений."),
	('LOC_SEN_UI_UNIT_MAN_SPREADS_TOOLTIP',	'ru_RU',	"Оставшиеся спреды"),
	--German
	('LOC_SEN_UI_UNIT_MAN_VIEW_UNITS',		'de_DE',	"Einheiten anzeigen"),	
	('LOC_SEN_UI_UNIT_MANAGEMENT_HEADER',	'de_DE',	"Abteilungsleitung"),	
	('LOC_SEN_UI_UNIT_MAN_LANDUNITS',		'de_DE',	"Landeinheiten"),	
	('LOC_SEN_UI_UNIT_MAN_AIRUNITS',		'de_DE',	"Lufteinheiten"),	
	('LOC_SEN_UI_UNIT_MAN_NAVALUNITS',		'de_DE',	"Marineeinheiten"),	
	('LOC_SEN_UI_UNIT_MAN_MILITARY_TAB',	'de_DE',	"Militär"),	
	('LOC_SEN_UI_UNIT_MAN_RELIGIOUS_TAB',	'de_DE',	"Religiös"),	
	('LOC_SEN_UI_UNIT_MAN_CIVILIAN_TAB',	'de_DE',	"Zivilistin"),
	('LOC_SEN_UI_UNIT_MAN_GO_TO_UNIT',		'de_DE',	"Gehe zur Einheit"),
	('LOC_SEN_UI_UNIT_MAN_UNIT_NAME',		'de_DE',	"Einheitenname"),
	('LOC_SEN_UI_UNIT_MAN_HEALTH_HEADER',	'de_DE',	"Gesundheit"),
	('LOC_SEN_UI_UNIT_MAN_CURRENT_COMMAND',	'de_DE',	"Aktueller Befehl"),
	('LOC_SEN_UI_UNIT_MAN_UPGRADE_PROMOTE',	'de_DE',	"Upgrade oder Aktion verfügbar"),
	('LOC_SEN_UI_UNIT_MAN_EXP_TOOLTIP',		'de_DE',	"Erfahrung:"),
	('LOC_SEN_UI_UNIT_MAN_NOMILITARYUNITS',	'de_DE',	"Sie haben derzeit keine Militäreinheiten"),
	('LOC_SEN_UI_UNIT_MAN_NORELIGIOUSUNITS','de_DE',	"Sie haben derzeit keine religiösen Einheiten"),
	('LOC_SEN_UI_UNIT_MAN_NOCIVILIANUNITS',	'de_DE',	"Sie verfügen derzeit über keine zivilen Einheiten"),
	('LOC_SEN_UI_UNIT_MAN_SPREADS_TOOLTIP',	'de_DE',	"Verbleibende Spreads");