INSERT OR REPLACE INTO LocalizedText
    (Tag,	Language,	Text)
VALUES
    -- English
    ('LOC_MOD_MLK_ENHANCEDTOWNFOCUSINFO',		'en_US',	'Enhanced Town Focus Info'),
    ('LOC_MOD_MLK_ENHANCEDTOWNFOCUSINFO_DESCRIPTION',	'en_US',	'An enhanced display of town focus yield bonuses in Civ7, showing detailed breakdowns of improvements, buildings, and trade routes that contribute to specialization bonuses.'),
    ('LOC_MOD_ETFI_SPECIAL_QUARTERS',		'en_US',	'Special Quarters'),
    ('LOC_MOD_ETFI_BUILDING_QUARTERS',		'en_US',	'Building Quarters'),
    ('LOC_MOD_ETFI_UNIQUE_QUARTERS',		'en_US',	'Unique Civilization Quarters'),
    ('LOC_MOD_ETFI_FULL_TILE_QUARTERS',		'en_US',	'Full-Tile Quarters'),
    ('LOC_MOD_ETFI_ERA_BONUS',		        'en_US',	'Era Bonus'),
    ('LOC_MOD_ETFI_IMPROVEMENT_WOODCUTTER',	'en_US',	'Woodcutter'),
    ('LOC_MOD_ETFI_IMPROVEMENT_MINE',		'en_US',	'Mine'),
    ('LOC_MOD_ETFI_IMPROVEMENT_FISHING_BOAT',	'en_US',	'Fishing Boat'),
    ('LOC_MOD_ETFI_IMPROVEMENT_FARM',		'en_US',	'Farm'),
    ('LOC_MOD_ETFI_IMPROVEMENT_PASTURE',		'en_US',	'Pasture'),
    ('LOC_MOD_ETFI_IMPROVEMENT_PLANTATION',	'en_US',	'Plantation'),
    ('LOC_MOD_ETFI_IMPROVEMENT_CAMP',		'en_US',	'Camp'),
    ('LOC_MOD_ETFI_IMPROVEMENT_CLAY_PIT',	'en_US',	'Clay Pit'),
    ('LOC_MOD_ETFI_IMPROVEMENT_QUARRY',		'en_US',	'Quarry'),
    ('LOC_MOD_ETFI_TRADE_ROUTES',		'en_US',	'Trade Routes'),
    ('LOC_MOD_ETFI_TRADE_CONNECTIONS',		'en_US',	'Connected Settlements'),
    ('LOC_MOD_ETFI_CONNECTED_CITIES',		'en_US',	'Cities'),
    ('LOC_MOD_ETFI_CONNECTED_TOWNS',		'en_US',	'Towns'),
    ('LOC_MOD_ETFI_BONUS_PER_CONNECTION',	'en_US',	'Bonus per connection'),
    ('LOC_MOD_ETFI_TOTAL_RESOURCES',	        'en_US',	'Total Resources'),
    ('LOC_MOD_ETFI_HAPPINESS_PER_RESOURCE',	'en_US',	'Happiness per Resource'),
    ('LOC_MOD_ETFI_RESOURCES',	        'en_US',	'Resources'),
    -- Japanese
    ('LOC_MOD_MLK_ENHANCEDTOWNFOCUSINFO',		'ja_JP',	'Enhanced Town Focus Info (専門化選択時の詳細な生産表示)'),
    ('LOC_MOD_MLK_ENHANCEDTOWNFOCUSINFO_DESCRIPTION',	'ja_JP',	'都市の専門化を選択する際に、改善施設、建物、交易路からの詳細なボーナス内訳を表示します。'),
    ('LOC_MOD_ETFI_SPECIAL_QUARTERS',		'ja_JP',	'特殊区画 (+1 ずつ)'),
    ('LOC_MOD_ETFI_BUILDING_QUARTERS',		'ja_JP',	'建物区画 (+1 ずつ)'),
    ('LOC_MOD_ETFI_UNIQUE_QUARTERS',		'ja_JP',	'文明固有の区画'),
    ('LOC_MOD_ETFI_FULL_TILE_QUARTERS',		'ja_JP',	'フルタイル区画'),
    ('LOC_MOD_ETFI_ERA_BONUS',		        'ja_JP',	'時代ボーナス'),
    ('LOC_MOD_ETFI_IMPROVEMENT_WOODCUTTER',	'ja_JP',	'木こり小屋'),
    ('LOC_MOD_ETFI_IMPROVEMENT_MINE',		'ja_JP',	'鉱山'),
    ('LOC_MOD_ETFI_IMPROVEMENT_FISHING_BOAT',	'ja_JP',	'漁船'),
    ('LOC_MOD_ETFI_IMPROVEMENT_FARM',		'ja_JP',	'農場'),
    ('LOC_MOD_ETFI_IMPROVEMENT_PASTURE',		'ja_JP',	'牧場'),
    ('LOC_MOD_ETFI_IMPROVEMENT_PLANTATION',	'ja_JP',	'プランテーション'),
    ('LOC_MOD_ETFI_IMPROVEMENT_CAMP',		'ja_JP',	'狩猟キャンプ'),
    ('LOC_MOD_ETFI_IMPROVEMENT_CLAY_PIT',	'ja_JP',	'粘土採掘場'),
    ('LOC_MOD_ETFI_IMPROVEMENT_QUARRY',		'ja_JP',	'採石場'),
    ('LOC_MOD_ETFI_TRADE_ROUTES',		'ja_JP',	'交易路'),
    ('LOC_MOD_ETFI_TRADE_CONNECTIONS',		'ja_JP',	'接続された居住地'),
    ('LOC_MOD_ETFI_CONNECTED_CITIES',		'ja_JP',	'都市'),
    ('LOC_MOD_ETFI_CONNECTED_TOWNS',		'ja_JP',	'町'),
    ('LOC_MOD_ETFI_BONUS_PER_CONNECTION',	'ja_JP',	'接続ごとのボーナス'),
    ('LOC_MOD_ETFI_TOTAL_RESOURCES',	        'ja_JP',	'資源の合計'),
    ('LOC_MOD_ETFI_HAPPINESS_PER_RESOURCE',	'ja_JP',	'資源ごとの幸福度'),
    ('LOC_MOD_ETFI_RESOURCES',	        'ja_JP',	'資源'),
    -- Italian
    ('LOC_MOD_MLK_ENHANCEDTOWNFOCUSINFO',		        'it_IT',	'Informazioni avanzate sulla specializzazione cittadina'),
    ('LOC_MOD_MLK_ENHANCEDTOWNFOCUSINFO_DESCRIPTION',	'it_IT',	'Visualizzazione avanzata dei bonus di produzione della specializzazione cittadina in Civ7, mostrando dettagli sugli edifici, i quartieri e le rotte commerciali che contribuiscono ai bonus di specializzazione.'),
    ('LOC_MOD_ETFI_SPECIAL_QUARTERS',		            'it_IT',	'Quartieri Speciali'),
    ('LOC_MOD_ETFI_BUILDING_QUARTERS',		            'it_IT',	'Quartieri Edificio'),
    ('LOC_MOD_ETFI_UNIQUE_QUARTERS',		            'it_IT',	'Quartieri Unici di Civiltà'),
    ('LOC_MOD_ETFI_FULL_TILE_QUARTERS',		            'it_IT',	'Quartieri a Tessera Intera'),
    ('LOC_MOD_ETFI_ERA_BONUS',		                    'it_IT',	'Bonus Epoca'),
    ('LOC_MOD_ETFI_IMPROVEMENT_WOODCUTTER',	            'it_IT',	'Segheria'),
    ('LOC_MOD_ETFI_IMPROVEMENT_MINE',		            'it_IT',	'Miniera'),
    ('LOC_MOD_ETFI_IMPROVEMENT_FISHING_BOAT',	        'it_IT',	'Peschereccio'),
    ('LOC_MOD_ETFI_IMPROVEMENT_FARM',		            'it_IT',	'Fattoria'),
    ('LOC_MOD_ETFI_IMPROVEMENT_PASTURE',	        	'it_IT',	'Pascolo'),
    ('LOC_MOD_ETFI_IMPROVEMENT_PLANTATION',	            'it_IT',	'Piantagione'),
    ('LOC_MOD_ETFI_IMPROVEMENT_CAMP',		            'it_IT',	'Campo'),
    ('LOC_MOD_ETFI_IMPROVEMENT_CLAY_PIT',	            'it_IT',	'Cava d''argilla'),
    ('LOC_MOD_ETFI_IMPROVEMENT_QUARRY',		            'it_IT',	'Cava'),
    ('LOC_MOD_ETFI_TRADE_ROUTES',		                'it_IT',	'Rotte commerciali'),
    ('LOC_MOD_ETFI_TRADE_CONNECTIONS',		            'it_IT',	'Collegamenti commerciali'),
    ('LOC_MOD_ETFI_CONNECTED_CITIES',		            'it_IT',	'Città'),
    ('LOC_MOD_ETFI_CONNECTED_TOWNS',		            'it_IT',	'Paesi'),
    ('LOC_MOD_ETFI_BONUS_PER_CONNECTION',	            'it_IT',	'Bonus per connessione'),
    ('LOC_MOD_ETFI_TOTAL_RESOURCES',	                    'it_IT',	'Risorse totali'),
    ('LOC_MOD_ETFI_HAPPINESS_PER_RESOURCE',	            'it_IT',	'Felicità per risorsa'),
    ('LOC_MOD_ETFI_RESOURCES',	                        'it_IT',	'Risorse'),
    -- Russian
    ('LOC_MOD_MLK_ENHANCEDTOWNFOCUSINFO',		'ru_RU',	'Enhanced Town Focus Info'),
    ('LOC_MOD_MLK_ENHANCEDTOWNFOCUSINFO_DESCRIPTION',	'ru_RU',	'Улучшенное отображение бонусов к доходу с городков при его специализации, с разбивкой по улучшениям, ресурсам, зданиям и торговым путям.'),
    ('LOC_MOD_ETFI_SPECIAL_QUARTERS',		'ru_RU',	'Уникальные Кварталы'),
    ('LOC_MOD_ETFI_BUILDING_QUARTERS',		'ru_RU',	'Кварталы'),
    ('LOC_MOD_ETFI_UNIQUE_QUARTERS',		'ru_RU',	'Цивилизационные Кварталы'),
    ('LOC_MOD_ETFI_FULL_TILE_QUARTERS',		'ru_RU',	'Полноклеточные Кварталы'),
    ('LOC_MOD_ETFI_ERA_BONUS',		        'ru_RU',	'Бонус Эпохи'),
    ('LOC_MOD_ETFI_IMPROVEMENT_WOODCUTTER',	'ru_RU',	'Лесоруб'),
    ('LOC_MOD_ETFI_IMPROVEMENT_MINE',		'ru_RU',	'Рудник'),
    ('LOC_MOD_ETFI_IMPROVEMENT_FISHING_BOAT',	'ru_RU',	'Рыбацкое судно'),
    ('LOC_MOD_ETFI_IMPROVEMENT_FARM',		'ru_RU',	'Ферма'),
    ('LOC_MOD_ETFI_IMPROVEMENT_PASTURE',		'ru_RU',	'Пастбище'),
    ('LOC_MOD_ETFI_IMPROVEMENT_PLANTATION',	'ru_RU',	'Плантация'),
    ('LOC_MOD_ETFI_IMPROVEMENT_CAMP',		'ru_RU',	'Лагерь'),
    ('LOC_MOD_ETFI_IMPROVEMENT_CLAY_PIT',	'ru_RU',	'Глиняная яма'),
    ('LOC_MOD_ETFI_IMPROVEMENT_QUARRY',		'ru_RU',	'Каменоломня'),
    ('LOC_MOD_ETFI_TRADE_ROUTES',		'ru_RU',	'Торговые пути'),
    ('LOC_MOD_ETFI_TRADE_CONNECTIONS',		'ru_RU',	'Связанные Поселения'),
    ('LOC_MOD_ETFI_CONNECTED_CITIES',		'ru_RU',	'Города'),
    ('LOC_MOD_ETFI_CONNECTED_TOWNS',		'ru_RU',	'Городки'),
    ('LOC_MOD_ETFI_BONUS_PER_CONNECTION',	'ru_RU',	'Бонус за Соединение'),  
    ('LOC_MOD_ETFI_TOTAL_RESOURCES',	        'ru_RU',	'Всего Ресурсов'),
    ('LOC_MOD_ETFI_HAPPINESS_PER_RESOURCE',	'ru_RU',	'Довольство за ресурс'),
    ('LOC_MOD_ETFI_RESOURCES',	        'ru_RU',	'Ресурсы'),
    -- Polish
    ('LOC_MOD_MLK_ENHANCEDTOWNFOCUSINFO',		'pl_PL',	'Rozszerzone Informacje o Miasteczkach'),
    ('LOC_MOD_MLK_ENHANCEDTOWNFOCUSINFO_DESCRIPTION',	'pl_PL',	'Przedstawia szczegółowe zestawienie ulepszeń, budynków, szlaków handlowych i połączeń między osiedlami, które zwiększają premie za specjalizację miasteczek.'),
    ('LOC_MOD_ETFI_SPECIAL_QUARTERS',		'pl_PL',	'Dzielnice Specjalne'),
    ('LOC_MOD_ETFI_BUILDING_QUARTERS',		'pl_PL',	'Dzielnice'),
    ('LOC_MOD_ETFI_UNIQUE_QUARTERS',		'pl_PL',	'Unikalne Dzielnice Cywilizacji'),
    ('LOC_MOD_ETFI_FULL_TILE_QUARTERS',		'pl_PL',	'Dzielnice Pełnopolowe'),
    ('LOC_MOD_ETFI_ERA_BONUS',		        'pl_PL',	'Mnożnik Epoki'),
    ('LOC_MOD_ETFI_IMPROVEMENT_WOODCUTTER',	'pl_PL',	'Drwal'),
    ('LOC_MOD_ETFI_IMPROVEMENT_MINE',		'pl_PL',	'Kopalnia'),
    ('LOC_MOD_ETFI_IMPROVEMENT_FISHING_BOAT',	'pl_PL',	'Łódź rybacka'),
    ('LOC_MOD_ETFI_IMPROVEMENT_FARM',		'pl_PL',	'Farma'),
    ('LOC_MOD_ETFI_IMPROVEMENT_PASTURE',		'pl_PL',	'Pastwisko'),
    ('LOC_MOD_ETFI_IMPROVEMENT_PLANTATION',	'pl_PL',	'Plantacja'),
    ('LOC_MOD_ETFI_IMPROVEMENT_CAMP',		'pl_PL',	'Obóz'),
    ('LOC_MOD_ETFI_IMPROVEMENT_CLAY_PIT',	'pl_PL',	'Glinianka'),
    ('LOC_MOD_ETFI_IMPROVEMENT_QUARRY',		'pl_PL',	'Kamieniołom'),
    ('LOC_MOD_ETFI_TRADE_ROUTES',		'pl_PL',	'Szlaki handlowe'),
    ('LOC_MOD_ETFI_TRADE_CONNECTIONS',		'pl_PL',	'Połączone Osiedla'),
    ('LOC_MOD_ETFI_CONNECTED_CITIES',		'pl_PL',	'Miasta'),
    ('LOC_MOD_ETFI_CONNECTED_TOWNS',		'pl_PL',	'Miasteczka'),
    ('LOC_MOD_ETFI_BONUS_PER_CONNECTION',	'pl_PL',	'Premia za połączenia'),
    ('LOC_MOD_ETFI_TOTAL_RESOURCES',	        'pl_PL',	'Zasoby Łącznie'),
    ('LOC_MOD_ETFI_HAPPINESS_PER_RESOURCE',	'pl_PL',	'Zadowolenie za Zasób'),
    ('LOC_MOD_ETFI_RESOURCES',	        'pl_PL',	'Zasoby'),
    -- Simplified Chinese
    ('LOC_MOD_MLK_ENHANCEDTOWNFOCUSINFO',		'zh_Hans_CN',	'增强城镇专业化信息'),
    ('LOC_MOD_MLK_ENHANCEDTOWNFOCUSINFO_DESCRIPTION',	'zh_Hans_CN',	'在《文明7》中增强显示的城镇专业化产出加成，展示改进、建筑和贸易路线对专业化加成的详细分解。'),
    ('LOC_MOD_ETFI_SPECIAL_QUARTERS',		'zh_Hans_CN',	'特殊区域'),
    ('LOC_MOD_ETFI_BUILDING_QUARTERS',		'zh_Hans_CN',	'建筑区域'),
    ('LOC_MOD_ETFI_UNIQUE_QUARTERS',		'zh_Hans_CN',	'独特文明区域'),
    ('LOC_MOD_ETFI_FULL_TILE_QUARTERS',		'zh_Hans_CN',	'全地块区域'),
    ('LOC_MOD_ETFI_ERA_BONUS',		        'zh_Hans_CN',	'时代加成'),
    ('LOC_MOD_ETFI_IMPROVEMENT_WOODCUTTER',	'zh_Hans_CN',	'伐木场'),
    ('LOC_MOD_ETFI_IMPROVEMENT_MINE',		'zh_Hans_CN',	'矿井'),
    ('LOC_MOD_ETFI_IMPROVEMENT_FISHING_BOAT',	'zh_Hans_CN',	'渔船'),
    ('LOC_MOD_ETFI_IMPROVEMENT_FARM',		'zh_Hans_CN',	'农场'),
    ('LOC_MOD_ETFI_IMPROVEMENT_PASTURE',		'zh_Hans_CN',	'牧场'),
    ('LOC_MOD_ETFI_IMPROVEMENT_PLANTATION',	'zh_Hans_CN',	'种植园'),
    ('LOC_MOD_ETFI_IMPROVEMENT_CAMP',		'zh_Hans_CN',	'营地'),
    ('LOC_MOD_ETFI_IMPROVEMENT_CLAY_PIT',	'zh_Hans_CN',	'黏土坑'),
    ('LOC_MOD_ETFI_IMPROVEMENT_QUARRY',		'zh_Hans_CN',	'采石场'),
    ('LOC_MOD_ETFI_TRADE_ROUTES',		'zh_Hans_CN',	'贸易路线'),
    ('LOC_MOD_ETFI_TRADE_CONNECTIONS',		'zh_Hans_CN',	'连接的定居点'),
    ('LOC_MOD_ETFI_CONNECTED_CITIES',		'zh_Hans_CN',	'城市'),
    ('LOC_MOD_ETFI_CONNECTED_TOWNS',		'zh_Hans_CN',	'城镇'),
    ('LOC_MOD_ETFI_BONUS_PER_CONNECTION',	'zh_Hans_CN',	'每个连接的加成'),
    ('LOC_MOD_ETFI_TOTAL_RESOURCES',	        'zh_Hans_CN',	'总资源'),
    ('LOC_MOD_ETFI_HAPPINESS_PER_RESOURCE',	'zh_Hans_CN',	'每个资源的幸福度'),
    ('LOC_MOD_ETFI_RESOURCES',	        'zh_Hans_CN',	'资源'),
    -- Korean
    ('LOC_MOD_MLK_ENHANCEDTOWNFOCUSINFO',		'ko_KR',	'Enhanced Town Focus Info (향상된 마을 전문화)'),
    ('LOC_MOD_MLK_ENHANCEDTOWNFOCUSINFO_DESCRIPTION',	'ko_KR',	'마을 전문화를 선택할 때 시설, 건물 및 교역로에서 자세한 보너스를 분석해 보여줍니다.'),
    ('LOC_MOD_ETFI_SPECIAL_QUARTERS',		'ko_KR',	'특수 지구'),
    ('LOC_MOD_ETFI_BUILDING_QUARTERS',		'ko_KR',	'건물 구역'),
    ('LOC_MOD_ETFI_UNIQUE_QUARTERS',		'ko_KR',	'문명 특유 구역'),
    ('LOC_MOD_ETFI_FULL_TILE_QUARTERS',		'ko_KR',	'타일 전체 점유 구역'),
    ('LOC_MOD_ETFI_ERA_BONUS',		        'ko_KR',	'유산 보너스'),
    ('LOC_MOD_ETFI_IMPROVEMENT_WOODCUTTER',	'ko_KR',	'벌목장'),
    ('LOC_MOD_ETFI_IMPROVEMENT_MINE',		'ko_KR',	'광산'),
    ('LOC_MOD_ETFI_IMPROVEMENT_FISHING_BOAT',	'ko_KR',	'어선'),
    ('LOC_MOD_ETFI_IMPROVEMENT_FARM',		'ko_KR',	'농장'),
    ('LOC_MOD_ETFI_IMPROVEMENT_PASTURE',		'ko_KR',	'목장'),
    ('LOC_MOD_ETFI_IMPROVEMENT_PLANTATION',	'ko_KR',	'플랜테이션'),
    ('LOC_MOD_ETFI_IMPROVEMENT_CAMP',		'ko_KR',	'야영지'),
    ('LOC_MOD_ETFI_IMPROVEMENT_CLAY_PIT',	'ko_KR',	'점토'),
    ('LOC_MOD_ETFI_IMPROVEMENT_QUARRY',		'ko_KR',	'채석장'),
    ('LOC_MOD_ETFI_TRADE_ROUTES',		'ko_KR',	'교역로'),
    ('LOC_MOD_ETFI_TRADE_CONNECTIONS',		'ko_KR',	'연결된 정착지'),
    ('LOC_MOD_ETFI_CONNECTED_CITIES',		'ko_KR',	'도시'),
    ('LOC_MOD_ETFI_CONNECTED_TOWNS',		'ko_KR',	'마을'),
    ('LOC_MOD_ETFI_BONUS_PER_CONNECTION',	'ko_KR',	'연결 당 보너스'),
    ('LOC_MOD_ETFI_TOTAL_RESOURCES',	        'ko_KR',	'총 자원'),
    ('LOC_MOD_ETFI_HAPPINESS_PER_RESOURCE',	'ko_KR',	'자원 당 행복도'),
    ('LOC_MOD_ETFI_RESOURCES',	        'ko_KR',	'자원');