INSERT OR REPLACE INTO LocalizedText
    (Tag,	Language,	Text)
VALUES
    -- English
    ('LOC_MOD_MLK_ENHANCEDTOWNFOCUSINFO',		'en_US',	'Enhanced Town Focus Info'),
    ('LOC_MOD_MLK_ENHANCEDTOWNFOCUSINFO_DESCRIPTION',	'en_US',	'An enhanced display of town focus yield bonuses in Civ7, showing detailed breakdowns of improvements, buildings, and trade routes that contribute to specialization bonuses.'),
    ('LOC_MOD_ETFI_SPECIAL_QUARTERS',		'en_US',	'Special Quarters'),
    ('LOC_MOD_ETFI_BUILDING_QUARTERS',		'en_US',	'Building Quarters'),
    ('LOC_MOD_ETFI_ERA_BONUS',		        'en_US',	'Era Bonus'),
    ('LOC_MOD_ETFI_IMPROVEMENT_WOODCUTTER',	'en_US',	'Woodcutter'),
    ('LOC_MOD_ETFI_IMPROVEMENT_MINE',		'en_US',	'Mine'),
    ('LOC_MOD_ETFI_IMPROVEMENT_FISHING_BOAT',	'en_US',	'Fishing Boat'),
    ('LOC_MOD_ETFI_IMPROVEMENT_FARM',		'en_US',	'Farm'),
    ('LOC_MOD_ETFI_IMPROVEMENT_PASTURE',		'en_US',	'Pasture'),
    ('LOC_MOD_ETFI_IMPROVEMENT_PLANTATION',	'en_US',	'Plantation'),
    ('LOC_MOD_ETFI_IMPROVEMENT_CAMP',		'en_US',	'Camp'),
    ('LOC_MOD_ETFI_IMPROVEMENT_CLAY_PIT',	'en_US',	'Clay Pit'),
    ('LOC_MOD_ETFI_IMPROVEMENT_QUARRY',		'en_US',	'Quarry'),
    ('LOC_MOD_ETFI_TRADE_ROUTES',		'en_US',	'Trade Routes'),
    ('LOC_MOD_ETFI_TRADE_CONNECTIONS',		'en_US',	'Connected Settlements'),
    ('LOC_MOD_ETFI_CONNECTED_CITIES',		'en_US',	'Cities'),
    ('LOC_MOD_ETFI_CONNECTED_TOWNS',		'en_US',	'Towns'),
    ('LOC_MOD_ETFI_BONUS_PER_CONNECTION',	'en_US',	'Bonus per connection'),
    ('LOC_MOD_ETFI_TOTAL_RESOURCES',	        'en_US',	'Total Resources'),
    ('LOC_MOD_ETFI_HAPPINESS_PER_RESOURCE',	'en_US',	'Happiness per Resource'),
    ('LOC_MOD_ETFI_RESOURCES',	        'en_US',	'Resources'),
    -- Japanese
    ('LOC_MOD_MLK_ENHANCEDTOWNFOCUSINFO',		'ja_JP',	'Enhanced Town Focus Info (専門化選択時の詳細な生産表示)'),
    ('LOC_MOD_MLK_ENHANCEDTOWNFOCUSINFO_DESCRIPTION',	'ja_JP',	'都市の専門化を選択する際に、改善施設、建物、交易路からの詳細なボーナス内訳を表示します。'),
    ('LOC_MOD_ETFI_SPECIAL_QUARTERS',		'ja_JP',	'特殊区画 (+1 ずつ)'),
    ('LOC_MOD_ETFI_BUILDING_QUARTERS',		'ja_JP',	'建物区画 (+1 ずつ)'),
    ('LOC_MOD_ETFI_ERA_BONUS',		        'ja_JP',	'時代ボーナス'),
    ('LOC_MOD_ETFI_IMPROVEMENT_WOODCUTTER',	'ja_JP',	'木こり小屋'),
    ('LOC_MOD_ETFI_IMPROVEMENT_MINE',		'ja_JP',	'鉱山'),
    ('LOC_MOD_ETFI_IMPROVEMENT_FISHING_BOAT',	'ja_JP',	'漁船'),
    ('LOC_MOD_ETFI_IMPROVEMENT_FARM',		'ja_JP',	'農場'),
    ('LOC_MOD_ETFI_IMPROVEMENT_PASTURE',		'ja_JP',	'牧場'),
    ('LOC_MOD_ETFI_IMPROVEMENT_PLANTATION',	'ja_JP',	'プランテーション'),
    ('LOC_MOD_ETFI_IMPROVEMENT_CAMP',		'ja_JP',	'狩猟キャンプ'),
    ('LOC_MOD_ETFI_IMPROVEMENT_CLAY_PIT',	'ja_JP',	'粘土採掘場'),
    ('LOC_MOD_ETFI_IMPROVEMENT_QUARRY',		'ja_JP',	'採石場'),
    ('LOC_MOD_ETFI_TRADE_ROUTES',		'ja_JP',	'交易路'),
    ('LOC_MOD_ETFI_TRADE_CONNECTIONS',		'ja_JP',	'接続された居住地'),
    ('LOC_MOD_ETFI_CONNECTED_CITIES',		'ja_JP',	'都市'),
    ('LOC_MOD_ETFI_CONNECTED_TOWNS',		'ja_JP',	'町'),
    ('LOC_MOD_ETFI_BONUS_PER_CONNECTION',	'ja_JP',	'接続ごとのボーナス'),
    ('LOC_MOD_ETFI_TOTAL_RESOURCES',	        'ja_JP',	'資源の合計'),
    ('LOC_MOD_ETFI_HAPPINESS_PER_RESOURCE',	'ja_JP',	'資源ごとの幸福度'),
    ('LOC_MOD_ETFI_RESOURCES',	        'ja_JP',	'資源'),
    -- Italian
    ('LOC_MOD_MLK_ENHANCEDTOWNFOCUSINFO',		        'it_IT',	'Informazioni avanzate sulla specializzazione cittadina'),
    ('LOC_MOD_MLK_ENHANCEDTOWNFOCUSINFO_DESCRIPTION',	'it_IT',	'Visualizzazione avanzata dei bonus di produzione della specializzazione cittadina in Civ7, mostrando dettagli sugli edifici, i quartieri e le rotte commerciali che contribuiscono ai bonus di specializzazione.'),
    ('LOC_MOD_ETFI_SPECIAL_QUARTERS',		            'it_IT',	'Quartieri Speciali'),
    ('LOC_MOD_ETFI_BUILDING_QUARTERS',		            'it_IT',	'Quartieri Edificio'),
    ('LOC_MOD_ETFI_ERA_BONUS',		                    'it_IT',	'Bonus Epoca'),
    ('LOC_MOD_ETFI_IMPROVEMENT_WOODCUTTER',	            'it_IT',	'Segheria'),
    ('LOC_MOD_ETFI_IMPROVEMENT_MINE',		            'it_IT',	'Miniera'),
    ('LOC_MOD_ETFI_IMPROVEMENT_FISHING_BOAT',	        'it_IT',	'Peschereccio'),
    ('LOC_MOD_ETFI_IMPROVEMENT_FARM',		            'it_IT',	'Fattoria'),
    ('LOC_MOD_ETFI_IMPROVEMENT_PASTURE',	        	'it_IT',	'Pascolo'),
    ('LOC_MOD_ETFI_IMPROVEMENT_PLANTATION',	            'it_IT',	'Piantagione'),
    ('LOC_MOD_ETFI_IMPROVEMENT_CAMP',		            'it_IT',	'Campo'),
    ('LOC_MOD_ETFI_IMPROVEMENT_CLAY_PIT',	            'it_IT',	'Cava d''argilla'),
    ('LOC_MOD_ETFI_IMPROVEMENT_QUARRY',		            'it_IT',	'Cava'),
    ('LOC_MOD_ETFI_TRADE_ROUTES',		                'it_IT',	'Rotte commerciali'),
    ('LOC_MOD_ETFI_TRADE_CONNECTIONS',		            'it_IT',	'Collegamenti commerciali'),
    ('LOC_MOD_ETFI_CONNECTED_CITIES',		            'it_IT',	'Città'),
    ('LOC_MOD_ETFI_CONNECTED_TOWNS',		            'it_IT',	'Paesi'),
    ('LOC_MOD_ETFI_BONUS_PER_CONNECTION',	            'it_IT',	'Bonus per connessione'),
    ('LOC_MOD_ETFI_TOTAL_RESOURCES',	                    'it_IT',	'Risorse totali'),
    ('LOC_MOD_ETFI_HAPPINESS_PER_RESOURCE',	            'it_IT',	'Felicità per risorsa'),
    ('LOC_MOD_ETFI_RESOURCES',	                        'it_IT',	'Risorse'),
    -- Russian
    ('LOC_MOD_MLK_ENHANCEDTOWNFOCUSINFO',		'ru_RU',	'Enhanced Town Focus Info'),
    ('LOC_MOD_MLK_ENHANCEDTOWNFOCUSINFO_DESCRIPTION',	'ru_RU',	'Улучшенное отображение бонусов к доходу с городков при его специализации, с разбивкой по улучшениям, ресурсам, зданиям и торговым путям.'),
    ('LOC_MOD_ETFI_SPECIAL_QUARTERS',		'ru_RU',	'Уникальные Кварталы'),
    ('LOC_MOD_ETFI_BUILDING_QUARTERS',		'ru_RU',	'Кварталы'),
    ('LOC_MOD_ETFI_ERA_BONUS',		        'ru_RU',	'Бонус Эпохи'),
    ('LOC_MOD_ETFI_IMPROVEMENT_WOODCUTTER',	'ru_RU',	'Лесоруб'),
    ('LOC_MOD_ETFI_IMPROVEMENT_MINE',		'ru_RU',	'Рудник'),
    ('LOC_MOD_ETFI_IMPROVEMENT_FISHING_BOAT',	'ru_RU',	'Рыбацкое судно'),
    ('LOC_MOD_ETFI_IMPROVEMENT_FARM',		'ru_RU',	'Ферма'),
    ('LOC_MOD_ETFI_IMPROVEMENT_PASTURE',		'ru_RU',	'Пастбище'),
    ('LOC_MOD_ETFI_IMPROVEMENT_PLANTATION',	'ru_RU',	'Плантация'),
    ('LOC_MOD_ETFI_IMPROVEMENT_CAMP',		'ru_RU',	'Лагерь'),
    ('LOC_MOD_ETFI_IMPROVEMENT_CLAY_PIT',	'ru_RU',	'Глиняная яма'),
    ('LOC_MOD_ETFI_IMPROVEMENT_QUARRY',		'ru_RU',	'Каменоломня'),
    ('LOC_MOD_ETFI_TRADE_ROUTES',		'ru_RU',	'Торговые пути'),
    ('LOC_MOD_ETFI_TRADE_CONNECTIONS',		'ru_RU',	'Связанные Поселения'),
    ('LOC_MOD_ETFI_CONNECTED_CITIES',		'ru_RU',	'Города'),
    ('LOC_MOD_ETFI_CONNECTED_TOWNS',		'ru_RU',	'Городки'),
    ('LOC_MOD_ETFI_BONUS_PER_CONNECTION',	'ru_RU',	'Бонус за Соединение'),  
    ('LOC_MOD_ETFI_TOTAL_RESOURCES',	        'ru_RU',	'Всего Ресурсов'),
    ('LOC_MOD_ETFI_HAPPINESS_PER_RESOURCE',	'ru_RU',	'Довольство за ресурс'),
    ('LOC_MOD_ETFI_RESOURCES',	        'ru_RU',	'Ресурсы');